### ISSUE TITLE
Filtering based on nested properties

### ISSUE THREAD

**Issue by habbes** [grafitto/grafitto-filter#3]
I want to suggest a feature that could be potentially useful, filtering based on nested properties.

For example, consider the following data:
```javascript
[{
   id: 1,
   name: {
       first: "Foo",
       last: "Bar"
   }
}]
```
Then the component could support filtering based on the last name with syntax like :
```html
<grafitto-filter where="name.last" like="bar">
```

**Comment by grafitto** [comment]
Filtering based on nested properties is now supported.
