### ISSUE TITLE
Filter array of primitives when where attribute not provided

### ISSUE THREAD

**Issue by habbes** [grafitto/grafitto-filter#5]
May I suggest another feature?

Allow the component to filter an array of simple strings as opposed to objects in which case the user would omit the `where` attribute.

Example:
Data:
```javascript
["Foo", "Bar", "This", "That"]
```
```html
<grafitto-filter items="{{data}}" like="th"></grafitto-filter>
```

**Comment by grafitto** [comment]
This feature is now available
