### ISSUE TITLE
Populate the dom after filtering the data

### ISSUE THREAD

**Issue by habbes** [grafitto/grafitto-filter#6]
I notice that you call the method to populate the dom inside the `_computeFiltered` method. Is there any reason for this? I propose that you let `_computerFiltered` be a simple function with as little side-effects as possible, which should make it easier to test and less unpredictable. I propose that you create an observer for the `filtered` property and populate the dom after being notified of the property's change through the observer. What do you think?

**Comment by habbes** [comment]
Similarly you can trigger then `filter` event outside of the function and inside an observer, before the dom is populated. But that's just a suggestion, don't know what you had in mind.

**Comment by grafitto** [comment]
`filter` event is now triggered in an observer, and the dom is populated by an observer as well
